'use strict';
const $=id=>document.getElementById(id);
let lastState=null,eventSource=null,reconnectTimer=null;
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>Number(n||0).toLocaleString('en-US');
const hz=v=>{const n=Number(v||0);return n?`${(n/1e6).toFixed(6)} MHz`:'—'};
const onoff=v=>v?'ON':'OFF';
function toast(msg,error=false){const t=$('toast');t.textContent=msg;t.className='toast show'+(error?' error':'');setTimeout(()=>t.className='toast',2200)}
async function post(path,body){try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):null});if(!r.ok)throw new Error(await r.text());const d=await r.json();if(d.state)render(d.state);return d}catch(e){toast(e.message,true);throw e}}
function badgeReasons(reasons){return (reasons||[]).filter(r=>!r.startsWith('snr ')).slice(0,4).map(r=>{const low=r.toLowerCase();let cls='badge';if(low.includes('new entity')||low.includes('new slot')||low.includes('new call')||low==='watchlist')cls+=' hot';else if(low.includes('unconfirmed'))cls+=' unconfirmed';return `<span class="${cls}">${esc(r.replace('new entity ','NEW DXCC ').replace('new entity','NEW DXCC').replace('new slot','NEW SLOT').replace('new call','NEW CALL').replace('slot unconfirmed','UNCONFIRMED').toUpperCase())}</span>`}).join('')||'<span class="badge">WORKED</span>'}
function renderCandidates(d){const current=d.candidates||[],fallback=d.last_cycle_candidates||[],rows=current.length?current:fallback,selected=d.selected_candidate||{};$('candidate-count').textContent=rows.length;$('selected-call').textContent=selected.call?`SELECTED ${selected.call}`:'NO SELECTION';$('candidate-empty').classList.toggle('hidden',rows.length>0);$('candidates-body').innerHTML=rows.map(c=>{const sel=selected.call===c.call&&selected.band===c.band;const snr=Number(c.snr);return `<tr class="${sel?'selected ':''}${!current.length?'stale':''}"><td><span class="kind ${esc(c.kind)}">${esc((c.kind||'').toUpperCase())}</span></td><td><span class="call">${esc(c.call)}</span></td><td>${esc(c.entity||'—')}</td><td>${esc(c.band||'—')} / ${esc(c.mode||'FT8')}</td><td>${badgeReasons(c.reasons)}</td><td><span class="snr ${snr>=-12?'good':'weak'}">${snr>0?'+':''}${snr}</span></td><td><span class="score">${Math.round(Number(c.score||0))}</span></td></tr>`}).join('')}
function renderSources(d){const rows=[{kind:'CTY.DAT',path:d.cty_path||'cty.dat',records:d.cty_entities||0,error:!(d.cty_entities>0)},...(d.history_sources||[])];$('sources-list').innerHTML=rows.map(s=>`<div class="source-row"><span class="source-dot ${s.error?'bad':''}"></span><div class="source-main"><strong>${esc(s.kind)}</strong><small title="${esc(s.path)}">${esc(s.path||'—')}${s.error?' — '+esc(s.error):''}</small></div><span class="source-count">${fmt(s.records)} REC</span></div>`).join('')||'<div class="empty-state">NO SOURCES</div>'}
function renderQsos(d){const rows=(d.qso_log||[]).slice().reverse().slice(0,10);$('qso-list').innerHTML=rows.map(q=>{const dt=new Date(Number(q.time||0)*1000);return `<div class="qso-row"><span class="qso-time">${dt.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</span><span><span class="qso-call">${esc(q.call)}</span><span class="qso-meta"> ${esc(q.entity||'')}</span></span><span class="qso-meta">${esc(q.band)} ${esc(q.mode)}</span></div>`}).join('')||'<div class="empty-state" style="height:100px">NO QSO THIS SESSION</div>'}
function renderNative(d){
 const n=d.native_control||{},req=n.requested||{},rep=n.reported||{},native=d.control_backend==='mshv_native';
 const capable=!!n.capable,confirmed=!!n.confirmed,armed=!!d.armed,ab=$('arm-button');
 ab.classList.remove('armed','disarmed','requested');
 if(!armed)ab.classList.add('disarmed');else if(confirmed)ab.classList.add('armed');else ab.classList.add('requested');
 $('arm-title').textContent=!armed?'DISARMED':confirmed?'ARMED / CONFIRMED':'ARM REQUESTED';
 $('arm-subtitle').textContent=!armed?'Monitor / Assist':confirmed?'MSHV Native Auto Active':'Waiting for MSHV acknowledgement';
 const nl=$('native-link');
 if(!native){nl.className='pill neutral';nl.innerHTML='<span class="dot"></span>LEGACY UDP';}
 else if(confirmed){nl.className='pill ok';nl.innerHTML='<span class="dot"></span>NATIVE CONFIRMED';}
 else if(capable){nl.className='pill warn';nl.innerHTML='<span class="dot"></span>NATIVE PENDING';}
 else{nl.className='pill error';nl.innerHTML='<span class="dot"></span>NATIVE NOT DETECTED';}
 $('n-capable').textContent=capable?'DETECTED':'NOT DETECTED';$('n-capable').className=capable?'ack-ok':'ack-bad';
 $('n-auto').textContent=`REQ ${onoff(req.auto_enabled)} / ACK ${onoff(rep.auto_enabled)}`;
 $('n-aseq').textContent=`REQ ${onoff(req.auto_seq)} / ACK ${onoff(rep.auto_seq)}`;
 $('n-mastd').textContent=`REQ ${onoff(req.multi_answer_std)} / ACK ${onoff(rep.multi_answer_std)}`;
 ['n-auto','n-aseq','n-mastd'].forEach((id,i)=>{const keys=['auto_enabled','auto_seq','multi_answer_std'];$(id).className=req[keys[i]]===rep[keys[i]]&&capable?'ack-ok':'ack-warn'});
 if(native){$('active-call').textContent='MSHV NATIVE';$('active-time').textContent=confirmed?'CONTROL ACKNOWLEDGED':armed?'WAITING FOR ACK':'IDLE / DISARMED';}
 return {native,capable,confirmed,armed};
}
function render(d){lastState=d;$('version').textContent='v'+(d.version||'0.4.0');const ns=renderNative(d);
 if(!ns.native){const armed=!!d.armed,ab=$('arm-button');ab.classList.toggle('armed',armed);ab.classList.toggle('disarmed',!armed);$('arm-title').textContent=armed?'ARMED':'DISARMED';$('arm-subtitle').textContent=armed?'Legacy UDP Auto':'Monitor / Assist';$('active-call').textContent=d.active_call||'—';$('active-time').textContent=d.active_call?`${Number(d.active_for||0).toFixed(1)}s • ${(d.active_kind||'QSO').toUpperCase()}`:'IDLE';}
 $('m-session').textContent=fmt(d.session_qsos);$('m-hour').textContent=`${fmt(d.hour_qsos)} / ${fmt(d.limits?.per_hour)} this hour`;$('m-history').textContent=fmt(d.history_qsos);$('m-entities').textContent=`${fmt(d.history_entities)} entities`;$('m-cty').textContent=fmt(d.cty_entities);$('m-cty-path').textContent=(d.cty_path||'CTY.DAT').split(/[\\/]/).pop();$('m-action').textContent=d.last_action||'IDLE';$('m-cq').textContent=ns.native?`Backend: MSHV native${ns.confirmed?' / confirmed':''}`:(d.last_cq_age==null?'CQ window —':`Last CQ ${d.last_cq_age}s ago`);
 document.querySelectorAll('[data-strategy]').forEach(b=>b.classList.toggle('active',b.dataset.strategy===d.operating_strategy));if(document.activeElement!==$('limit-hour'))$('limit-hour').value=d.limits?.per_hour??20;if(document.activeElement!==$('limit-session'))$('limit-session').value=d.limits?.per_session??200;
 const s=d.status||{},linked=!!d.instance;$('radio-link').className='pill '+(linked?'ok':'neutral');$('radio-link').innerHTML=`<span class="dot"></span>${linked?'MSHV LINKED':'MSHV WAITING'}`;$('s-instance').textContent=d.instance||'—';$('s-mode').textContent=s.mode||'—';$('s-dial').textContent=hz(s.dial_frequency);$('s-dx').textContent=s.dx_call||'—';$('s-tx').textContent=s.transmitting?'TX':s.tx_enabled?'AUTO / RX':'RX';$('s-tx').style.color=s.transmitting?'var(--red)':s.tx_enabled?'var(--amber)':'var(--green)';$('s-df').textContent=(s.rx_df!=null||s.tx_df!=null)?`${s.rx_df??'—'} / ${s.tx_df??'—'} Hz`:'—';
 const t=d.transport||{};$('mshv-packets').textContent=`${fmt(t.received)} packets`;const r=d.relay||{};$('wrl-link').className='pill '+(r.enabled===false?'neutral':r.last_error?'error':'ok');$('wrl-link').innerHTML=`<span class="dot"></span>${r.enabled===false?'WRL DISABLED':r.last_error?'WRL ERROR':'WRL ROUTER OK'}`;$('route-address').textContent=`${r.listen||'—'} → ${r.forward||'—'}`;$('r-rx').textContent=fmt(r.received);$('r-fwd').textContent=fmt(r.forwarded);$('r-wsjt').textContent=fmt(r.wsjt);$('r-adif').textContent=fmt(r.adif);$('r-latency').textContent=r.latency_ms_avg!=null?`${Number(r.latency_ms_avg).toFixed(2)} ms`:'—';$('r-jitter').textContent=r.jitter_ms!=null?`${Number(r.jitter_ms).toFixed(2)} ms`:'—';$('relay-rate').textContent=`${fmt(r.received)} pkt`;$('forwarded-label').textContent=`${fmt(r.forwarded)} forwarded`;const er=$('relay-error');er.textContent=r.last_error||d.last_error||'';er.classList.toggle('hidden',!er.textContent);renderCandidates(d);renderSources(d);renderQsos(d)}
function connect(){if(eventSource)eventSource.close();eventSource=new EventSource('/events');eventSource.onmessage=e=>{try{render(JSON.parse(e.data))}catch(err){console.error(err)}};eventSource.onerror=()=>{eventSource.close();clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connect,1500)}}
document.querySelector('[data-action="arm"]').addEventListener('click',()=>post(lastState?.armed?'/api/disarm':'/api/arm'));
document.querySelector('[data-action="halt"]').addEventListener('click',()=>post('/api/halt'));
document.querySelectorAll('[data-strategy]').forEach(b=>b.addEventListener('click',()=>post('/api/strategy',{strategy:b.dataset.strategy}).then(()=>toast(`Strategy: ${b.dataset.strategy.toUpperCase()}`))));
$('save-limits').addEventListener('click',()=>post('/api/limits',{per_hour:Number($('limit-hour').value),per_session:Number($('limit-session').value)}).then(()=>toast('TX limits updated')));
setInterval(()=>{$('utc-clock').textContent=new Date().toISOString().slice(11,19)+' UTC'},500);connect();
